# Use the official Node.js image as the base image
FROM node:18-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json (if available)
COPY package*.json ./

# Install the project dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Run Prisma migrations and generate Prisma client
RUN npx prisma migrate deploy 

# Generate Prisma client

RUN npx prisma generate

# Compile TypeScript code
RUN npx tsc -b

# Expose the port the app runs on
EXPOSE 3000

# Set the default command to run the application
CMD ["npm", "start"]
